import { type Settings } from "./types/Settings"

const defaultSettings:Settings = {
    antennaSelected: 0,
    enableTagAccessStatus: 0,
    DPOState: 0,
    enableTagAntennaID: 0,
    enableTagCRC: 0,
    enableTagXPC: 0,
    enableTagPC: 0,
    enableTagRSSI: 0,
    enableTagSeenCount: 0,
    enableTagUTCTimeStamp: 0,
    invMemBank: undefined,
    lockField: undefined,
    lockPrivilege: undefined,
    matchPattern: 'A',
    newTagID: undefined,
    tagOffset: 0,
newAccessPassword: undefined,
    newKillPassword: undefined,
    performStateAwareSingulation: 0,
    preFilterStateAwareAction: undefined,
    preFilterTarget: undefined,
    preFilterStateUnawareAction: 'SELECT_NOT_UNSELECT',
    preFilterBitCount: undefined,
    preFilterBitOffset: 32,
    preFilterHexPattern: undefined,
    preFilerID: undefined,
    preFilterMemBank: 'EPC',
    startPeriod: 0,
    readerID: 'RFID1',
    reportTrigger: 1,
    singulationSession: undefined,
    singulationTagPopulation: undefined,
    singulationSLFlag: undefined,
    startTriggerType: 'immediate',
    stopDuration: undefined,
    stopObservationCount: undefined,
    stopTriggerType: undefined,
    tagByteOffset: 0,
    tagID: undefined,
    tagKillPassword: undefined,
    tagMemBank: 'EPC',
    tagoffset: 0,
    tagPassword: '00000000',
    tagPatternAByteOffset: 4,
    tagPatternAHexMask: undefined,
    tagPatternAHexPattern: undefined,
    tagPatternBByteOffset: 4,
    tagPatternBHexPattern: undefined,
    tagPatternBMemBank: undefined,
    tagPatternAMemBank: 'EPC',
    tagReadSize: 0,
    tagWriteData: undefined,
    transpitPower: undefined,
    transport: 'serial',
    useAccessFilter: 0,
    useSoftTrigger: 0
}
    
export default defaultSettings